### ISSUE TITLE
Start date of CFP should be January 20

### ISSUE THREAD

**Issue by katrina376** [sitcon-tw/2021#4]
The starting date of the CFP should be 2021/1/20 (Wed). The date is mentioned both in the [landing page](https://sitcon.org/2021/cfp) and the [CFP instruction](https://sitcon.org/2021/cfp/news#)

**Comment by denny0223** [comment]
https://github.com/sitcon-tw/2021/commit/104d0df1af2f1367d694b77de5a66e4479b56d36

https://github.com/sitcon-tw/2021/commit/871e72e3b21b6138177b67a829b792c5618fb5b2
