### ISSUE TITLE
Split Chinese web font file or consider disable it

### ISSUE THREAD

**Issue by Inndy** [sitcon-tw/2021#9]
需要十秒的時間下載字體檔案，而且對於流量有限的行動網路使用者很不友善

使用中文字體請考慮把檔案切開，只留下有用到的字就好

![telegram-cloud-photo-size-5-6280673661153292201-x](https://user-images.githubusercontent.com/3402337/113278442-82eaff80-9314-11eb-82a2-74cbee60d788.jpg)

**Comment by rschiang** [comment]
如果有需要用到很多字重的話，感覺可以試試看用系統的 font stack，像是思源宋體的基礎字型 Hiragino Mincho (?)
不過可能就 macOS/iOS 跟 Linux（本來就有思源宋）有而已 🤔
